import { createRequire } from 'node:module';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const require = createRequire('C:/Users/Administrator/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/package.json');
const { chromium } = require('playwright');
const browser = await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
const page = await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'light'});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
fs.mkdirSync('qa',{recursive:true});
await page.goto('http://127.0.0.1:1313/');
await page.screenshot({path:'qa/home-desktop.png',fullPage:true});
assert.equal(await page.locator('.home-grid .post-row').count(),1);
await page.locator('#theme-toggle').click();
assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
await page.reload();
assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
await page.screenshot({path:'qa/home-dark.png',fullPage:true});
await page.locator('#theme-toggle').click();
await page.goto('http://127.0.0.1:1313/search/?q=Hugo');
await page.waitForFunction(()=>document.querySelector('#search-status').textContent.includes('找到'));
assert.equal(await page.locator('#search-results article').count(),1);
await page.locator('#search-input').fill('no-such-article-xyz');
await page.waitForFunction(()=>document.querySelector('#search-status').textContent.includes('没有找到'));
await page.locator('#search-input').fill('<img src=x onerror=alert(1)>');
await page.waitForFunction(()=>document.querySelector('#search-status').textContent.includes('没有找到'));
assert.equal(await page.locator('#search-results img').count(),0);
await page.goto('http://127.0.0.1:1313/posts/rebuilding-this-blog/');
assert.equal(await page.locator('.toc a').count(),4);
await page.context().grantPermissions(['clipboard-read','clipboard-write']);
await page.locator('.copy-code').first().click();
assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).trim(),'hugo server -D');
await page.screenshot({path:'qa/article-desktop.png',fullPage:true});
const urls=['/','/posts/','/projects/','/about/','/creative/','/oc/','/gallery/','/tags/','/categories/','/404.html'];
const map = JSON.parse(fs.readFileSync('public/index.json','utf8'));
assert.equal(map.length,1);
for(const dir of fs.readdirSync('../yuukage-original-build/notes')) urls.push('/notes/'+dir+'/');
for(const url of urls){const response=await page.goto('http://127.0.0.1:1313'+url);assert.equal(response.status(),200,url);}
const rss=fs.readFileSync('public/posts/index.xml','utf8');
assert(rss.includes('https://yuukage.com/posts/rebuilding-this-blog/'));
await page.setViewportSize({width:390,height:844});
for(const url of ['/','/posts/','/projects/','/about/','/search/','/posts/rebuilding-this-blog/','/creative/','/gallery/']){
 await page.goto('http://127.0.0.1:1313'+url);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Overflow: '+url);
}
await page.goto('http://127.0.0.1:1313/');
await page.screenshot({path:'qa/home-mobile.png',fullPage:true});
assert.deepEqual(errors,[]);
await browser.close();
console.log('Passed: build output, 5 legacy URLs, navigation, RSS, search including unsafe input, theme persistence, TOC, mobile overflow, browser errors.');
